[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "freetype",
  "freetype.dev",
  "harfbuzz",
  "ca-certificates",
  "ttf-opensans",
  "glib",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "libXcomposite",
  "libXdamage",
  "libXext",
  "libXfixes",
  "libXrandr",
  "libxkbcommon",
  "mesa",
  "pango",
  "expat",
  "xorg.libX11",
  "xorg.libXcursor",
  "xorg.libXrender",
  "alsa-lib"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/run/current-system/sw/bin/chromium"
